# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84584a3ac14efeac4025116d96d94b3cf7c4caef8e0696d293698a87d65e0667c72edbb95745d2d245e88c8167a7e0868329f805ceb6e5cda0aa2edce64ddd4d

test:
  secret_key_base: 013c7c3ebe51968577b822886de1de5a3692ed81b1edecedba5645a15cdd3c721b335d6d37883eea5ef6a4d943ce3a2e1adab82d3fc74393b6a1a0d9d19a4fff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
